### ISSUE TITLE
Change headings colors

### ISSUE THREAD

**Issue by Daneel87** [chaudharydeepanshu/clean_calendar#1]
I'd like to have an option to change styling for headings

**Comment by chaudharydeepanshu** [comment]
Nice suggestion. As soon as I have an update, I'll let you know. I'll be working on it.

Thank you.

**Comment by chaudharydeepanshu** [comment]
I have updated the package to support Weekday's customizations. More customizations for months, calendar controllers, and different styles for headers will also be added soon.

You can use the weekdays customization like this:-
```dart
  weekdaysProperties: WeekdaysProperties(
                generalWeekdaysDecoration:
                    WeekdaysDecoration(weekdayTextColor: Colors.red),
                sundayDecoration: WeekdaysDecoration(
                    weekdayTextColor: Colors.green,
                    weekdayTextStyle:
                        Theme.of(context).textTheme.headlineMedium),
                saturdayDecoration: WeekdaysDecoration(
                    weekdayTextColor: Colors.green,
                    weekdayTextStyle:
                        Theme.of(context).textTheme.headlineMedium),
),
```

Also, keep in mind that this update contains a few breaking changes(see changelog) which can be easily tackled.

If you have any queries then let me know.
Thank you.

**Comment by chaudharydeepanshu** [comment]
Added `headerProperties` for changing properties of the header section in version 1.1.0. 

This includes customization of the month and year colour and text style, and customization for the navigator buttons icon.

| <pre>CleanCalendar(<br />  headerProperties: HeaderProperties(<br />    monthYearDecoration: MonthYearDecoration(<br />      monthYearTextColor: Colors.amber,<br />      monthYearTextStyle: Theme.of(context).textTheme.labelMedium,<br />    ),<br />    navigatorDecoration: NavigatorDecoration(<br />      navigatorResetButtonIcon: const Icon(<br />        Icons.restart_alt,<br />        color: Colors.amber,<br />      ),<br />      navigateLeftButtonIcon: const Icon(<br />        Icons.arrow_circle_left,<br />        color: Colors.amber,<br />      ),<br />      navigateRightButtonIcon: const Icon(<br />        Icons.arrow_circle_right,<br />        color: Colors.amber,<br />      ),<br />    ),<br />  ),<br />)</pre> |
|:---|
| <img src="https://user-images.githubusercontent.com/85361211/214251692-d8cfb076-a185-4d9d-9b6b-81700023dd78.jpeg" width="400" />  |
