### ISSUE TITLE
ERROR: The method 'copyWith' isn't defined for the type 'DateTime'.

### ISSUE THREAD

**Issue by Daneel87** [chaudharydeepanshu/clean_calendar#5]
had to stick with version pre 1.0.0 because this error is present on 1.x.x

**Comment by chaudharydeepanshu** [comment]
@Daneel87  I have uploaded a new version with the fix [1.0.2 ](https://pub.dev/packages/clean_calendar).

Sorry, for this issue. I forgot that I was using the flutter master channel when coding that update and recently in Dart 2.19 support for DateTime.copyWith was added(https://github.com/dart-lang/sdk/issues/24644) which lead to this issue.
And For now, I added an extension method so it will still work with the older versions of darts.

Thank you for reporting the issue.
